version: "3.8"
services:
  database:
    image: "library/postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=${DATABASE_USERNAME}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
  servermanager:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    ports:
      - "8080:8080"
      - "25565:25565"
      - "25566:25566"
      - "25567:25567"
    environment:
      - 'DATABASE_USERNAME=${DATABASE_USERNAME}'
      - 'DATABASE_PASSWORD=${DATABASE_PASSWORD}'
      - 'SECURITY_cookieSecretEncryptKey=${COOKIE_ENCRYPT_KEY}'
      - 'SECURITY_cookieSecretSignKey=${COOKIE_SIGN_KEY}'
      - 'SECURITY_clientId=${GOOGLE_CLIENT_ID}'
      - 'SECURITY_clientSecret=${GOOGLE_CLIENT_SECRET}'
      - 'LOCALRUNNER_DOMAIN=${LOCAL_RUNNER_DOMAIN}'
      - 'HOST_HOSTNAME=${HOSTNAME}'
    volumes:
    - ./rundata:/minecraftservermanager
    restart: always