apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: msm-app
    apiGroup: ""
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io
