apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  storageClassName: ""
  volumeName: db-pv
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
