apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  storageClassName: ""
  claimRef:
    name: db-pvc
    namespace: default
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /data/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube